### ISSUE TITLE
Incluir texto salientando que a PodCodar eh gratis

### ISSUE THREAD

**Issue by fmagesty** [podcodar/webapp#104]
## Descrição

Adicionar em algum lugar do site que a PodCodar eh gratis

Assim novos visitantes que nao sabem do que se trata a PodCodar nao precisam pensar como pensamos por padrao, achando que sera um servico pago

Talvez seja ate interessante dizer que a pessoa pode doar se quiser. Que eh o que realmente representa a realidade do que acontece na PodCodar

**Comment by marco-souza** [comment]
Precisamos definir como ficaria esse texto antes de iniciar a implementação

**Comment by fmagesty** [comment]
Opa, vou fazer um esboço aqui agora pq em 10min tenho a standup mas acho que nao precisa ser nada muito grande nao.Uma sugestao pegando o texto atual de base e o texto da issue em negrito/italico, bem simples:

> Somos uma comunidade de tecnologia e computação que ensina programação com foco na formação de profissionais. Existimos para democratizar o conhecimento e o acesso às oportunidades de trabalho na área de tecnologia. _**A PodCodar é e vai continuar sendo grátis para todos, cobrando somente a sua dedicação. Quem quiser contribuir monetariamente também pode doar a quantia que quiser. Todas as doações são convertidas em bolsas de estudo para ajudar outros membros a continuarem estudando e construindo juntos esta comunidade**_

So um esboço mesmo pra dar um norte mas ve ai o que ces acham, acho que ficou ate muito grande, eu tava pensando em algo mais sucinto mesmo, sem precisar elaborar. so pra pessoa saber que nao eh pago mesmo pq isso poderia desanimar muita gente que ta começando. Por outro lado tem gente que nao leva a serio pela mesma razao mas isso ja eh outra questao haha. Foi ate bom receber a notificacao aqui que vo dar uma lida no projeto dps so pra ver cumé q ta atualmente. noisx

**Comment by marco-souza** [comment]
Mandou bem! Tarefinha ja ta no backlog

**Comment by fmagesty** [comment]
> Mandou bem! Tarefinha ja ta no backlog

uai se pa eu ate faco ela. eh bom q mexo um tikin no projeto. vo atualizar ele aqui e rodar ai se tiver tudo certo eu adiciono e faco o PR entao :D

**Comment by fmagesty** [comment]
uai, nao encontrei ela no backlog nao. fiquei na duvida se encaixo o texto igual mandei ali em cima mas era pra ser so o esboço ali. vou fazer e mandar o PR disso agora pq tenho ctz q se deixar pra depois eu vou esquecer. pelo menos no PR da pra lembrar ou ver como altera. tentei ler o pr atual do zenha tb mas preciso ler melhor como ta a codebase atual pra poder dar pitaco direito pq mudou bastante coisa mas eh bom ver q ta sempre ficando cada vez melhor :3

vo mandar aq

**Comment by frattezi** [comment]
Não está sendo trabalhado a um tempo, vou fechar
