### ISSUE TITLE
nova issue: acessibilidade ao icone de mudar de lingua 

### ISSUE THREAD

**Issue by vzsoares** [podcodar/webapp#111]
simbolo de mudar de lingua nao esta por padrao em todos sistemas por exemplo meu manjaro .
 sugiro usar um simplo externo como os demais (;
 
 
![image](https://user-images.githubusercontent.com/86134825/164791696-f238aead-8ac6-4245-a12c-fff3a33504f7.png)

**Comment by marco-souza** [comment]
Sobre isso, a gente tava considerando remover esse botao e deixar a apenas em pt-br. podemos discutir na nossa planning

**Comment by marco-souza** [comment]
Decidimos proceguir com a criação de novos icones. 

![Image](https://user-images.githubusercontent.com/4452113/167962213-54ef6354-fb6e-4f9e-af63-11dbe920227c.png)

![Image](https://user-images.githubusercontent.com/4452113/167962221-456b1748-80ba-4330-954d-203a99729ece.png)


Precisamos de:
- [ ] achar svg para as banderilhas (US, BR)
- [ ] Implementar `BRFlagIcon` &  `USFlagIcon`
- [ ] Subistituir conteúdo do botão por novos icone

**Comment by vzsoares** [comment]
![image](https://user-images.githubusercontent.com/86134825/168157385-c02fd8f4-8773-41fa-a02f-ffdb48432964.png)
