### ISSUE TITLE
Atualizar texto de mentorias

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#113]
Desde que criamos a pagina, tivemos algumas alterações nos fluxos e mentorias.

O objetivo dessa tarefa é atualizar os textos de mentoria para se adequar ao nosso modelo atual

- [x] Remover mentoria de dupla
- [x] Remover mentoria personalizada
- [x] Adicionar mentoria de trilhas
- [x] Adicionar mentoria de mercado

**Comment by vzsoares** [comment]
closed by #122
