### ISSUE TITLE
Atualizar atualizar perfil pessoal no site

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#114]
Como Membro do time de desenvolvimento, devemos atualizar nosso perfil publico na pagina de membros.

Essa tarefa deve ser feita por todos os desenvolvedores!

Link: https://podcodar.com/app/add-member

> Tanto github quanto linkedin precisam apenas do **username**, não o link do perfil.

Depois de atualizar seu perfil, deixe um comentário nesse card para ficar registrado

**Comment by vzsoares** [comment]
atualizei o meu !!!

**Comment by marco-souza** [comment]
@Guilherme-BS atualiza o seu tbm e ai podemos fechar essa tarefa

**Comment by marco-souza** [comment]
@vzsoares lembra de puxar a tarefa para in progress quando iniciar
