### ISSUE TITLE
Atualizar dependencias

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#115]
O objetivo dessa tarefa é atualizar as dependencias do sistema

Links:
- https://classic.yarnpkg.com/lang/en/docs/cli/upgrade/
- https://valchan.com.br/update-package-json/

**Comment by vzsoares** [comment]
fui tentar fazer , e na hora de dar push deu ruim 
tinha dado um erro diferente antes mas agr mudou
![image](https://user-images.githubusercontent.com/86134825/168390225-5d090083-aeb6-48ec-b9c2-01c860b4bc31.png)

**Comment by vzsoares** [comment]
uns errro mto loko , parece q é tudo de typescript
![image](https://user-images.githubusercontent.com/86134825/168390884-f1ade35f-07b2-44b0-a0f7-166ca13bd7ff.png)

**Comment by marco-souza** [comment]
Eh, tem que ir vendo caso a caso. O primeiro ali ta reclamando de multiplos filhos, ai tem que colocar os childrens dele dentro de um fargment.

O segundo nao sei, teria que ir testando.

**Comment by vzsoares** [comment]
colocando em fragment quebra a funcionalidade de usar ` , providers` . doidera pura

**Comment by marco-souza** [comment]
eh, tem que mexer no reducer, talvez desfazer ele, ou adicionar algum tipo faltando

**Comment by vzsoares** [comment]
o reducer vc quer dizer o arquivo esse [arquivo](https://github.com/podcodar/webapp/blob/e29538154a00fda5c44ca8d84c656b19d6b6b699/packages/utils/react.tsx#L8)?? sera que tem a ver com esse trem de es-lint [aqui](https://github.com/podcodar/webapp/blob/e29538154a00fda5c44ca8d84c656b19d6b6b699/packages/utils/react.tsx#L8)

**Comment by marco-souza** [comment]
isso, o reducer que ta nesse [arquivo](https://github.com/podcodar/webapp/blob/e29538154a00fda5c44ca8d84c656b19d6b6b699/packages/utils/react.tsx#L16). o reducer ta embrulhando um componente numa lista de providers, colocando um provider dentro do outro. Não sei se o TS lida bem com isso, pode ser o motivo de ta dando erro.

- for reference: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

Essa regra do eslint eh outra coisa. Ela evita de ter que descrever todas as dependencias de um useEffect
