### ISSUE TITLE
Adicionar uma tabela de testimonials no DB e salvar alguns testemunhos

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#125]

**Comment by vzsoares** [comment]
pensei inicialmente em criar um Form e pedir para que quem quisesse que preenchesse , mas a duvida é quais dados são necessarios? 
- [ ] nome
- [ ] testemunho
- [ ] foi bolsista

**Comment by marco-souza** [comment]
Acho que isso pode vir numa V2. Nesse primeiro momento seria mais pegar nossos testemunhos pra popular a página.

Esses forms, acho que seria bom a gente pensar em uma pagina privada/interna, pois geralmente são dados pessoais que conseguimos capturar boa parte dele no processo de cadastro

**Comment by marco-souza** [comment]
BTW, a coleta de dados sera feita nessa issue: https://github.com/podcodar/webapp/issues/128

**Comment by vzsoares** [comment]
@marco-souza  preciso saber como acessar o DB para adicionar alguns testemunhos

**Comment by marco-souza** [comment]
Faz um pair com o @Guilherme-BS que ele ta acessando o DB já, ai vocês já podem ir populando o banco

**Comment by vzsoares** [comment]
foram adicionados alguns place holder no db entao acho q essa issue ja foi
