### ISSUE TITLE
Coletar testemunhos

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#128]
# Description

Coletar feedbacks para preencher os cards da pagina principal

**Comment by marco-souza** [comment]
E ai galera, como estamos aqui?

**Comment by marco-souza** [comment]
Podemos antes de fazer uma interface para coleta de dados, apenas inserir os testimonials no banco. 
Basta pegar quem responder o form e popular manualmente ou com um script.

**Comment by vzsoares** [comment]
ainda sem testemunhos , vou ver com o mamao pra gente fomentar a glr

**Comment by marco-souza** [comment]
Acho que podemos começar com os nosso próprios testemunhos. Se pegar o seu, @Guilherme-BS e @Filipe-barbosa já conseguimos o suficiente pra apresentar hoje

**Comment by Guilherme-BS** [comment]
vo trombar com o zenha hj mais tarde pra tirar umas duvidas e montarmos uma estrategia pra pegar uns testemunhos

**Comment by vzsoares** [comment]
#137 merged , agr so' questao de divulgar e coletar os testemunhos
