### ISSUE TITLE
fix build error

### ISSUE THREAD

**Issue by vzsoares** [podcodar/webapp#139]
build error when pushing to branches 
![image](https://user-images.githubusercontent.com/86134825/178027485-8f5c3156-4876-4bf7-9fda-73563647b4fa.png)

#137

**Comment by fmagesty** [comment]
ue @vzsoares 
a primeira vista achei q fosse um erro de GIT mas depois vi q foi a build q ficou chateada. tenta dar uma olhada nisso aqui:
![image](https://user-images.githubusercontent.com/28074722/178034353-bb6a6207-d0b1-4a9d-b88d-833549c9d1e5.png)
