### ISSUE TITLE
Trocar imagem de 404 do webapp

### ISSUE THREAD

**Issue by frattezi** [podcodar/webapp#147]
É necessário atualizar a Lottie Animation que estamos utilizando na page de 404 do webapp.
Eu havia feito [uma alteração](https://github.com/podcodar/webapp/pull/145), porém, vamos aguardar uma nova imagem, e é legal alguém da mentoria pegar esta task!

PS: diferentemente do que fiz, no PR linkado, você pode deletar a animação anterior e apenas adicionar a nova no lugar, vou anexar a nova animação nesta task

**Comment by frattezi** [comment]
Aguardando raposa prover a próxima imagem

**Comment by fmagesty** [comment]
Opa, ele falou que tem a lottie animation la mas n sabe onde ta. no aguardo pra ele mandar aqui agora

**Comment by marco-souza** [comment]
Fechando isso pois lottie continua quebrado pro next :// vamos ter que fazer algum workaround
