### ISSUE TITLE
[onboarding] review and run project

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#171]
Clone and run our `webpp` projects

- access https://github.com/podcodar/webapp
- clone
- install dependencies (yarn or bun install)
- decrypt var envs (bun decrypt)
- run project (bun dev)

**Comment by marco-souza** [comment]
@AlexKHecht how is it going?
Let me know if you need any help with your setup.

Also, as an additional task, it would be great if you could participate in code reviews. There are a few discussions that I believe would be beneficial for your onboarding.

**Comment by AlexKHecht** [comment]
> [@AlexKHecht](https://github.com/AlexKHecht) how is it going? Let me know if you need any help with your setup.
> 
> Also, as an additional task, it would be great if you could participate in code reviews. There are a few discussions that I believe would be beneficial for your onboarding.

Thanks ! Tbh all of this is very new to me —including your message that I've just discovered, my bad— which is taking some getting used to.
I'll try to participate in some way in the code reviews, thanks @marco-souza !

**Comment by AlexKHecht** [comment]
Btw, I've finished setting up the the webapp, and I've created a branch to update the repo's readme to include some Windows specific stuff. I'll link the PR back to this issue, what do you think ?

**Comment by vzsoares** [comment]
Genius thing to gpg the .env. Just made me want to use it everywhere, but is it safe?? What about brute force? Should i thrust this method for things like db passwords? @marco-souza

**Comment by vzsoares** [comment]
> Clone and run our `webpp` projects
> 
> * access https://github.com/podcodar/webapp
> * clone
> * install dependencies (yarn or bun install)
> * decrypt var envs (bun decrypt)
> * run project (bun dev)

better version!?

* git clone https://github.com/podcodar/webapp.git
* install dependencies (yarn or bun install)
* decrypt var envs (yarn or bun decrypt)
* run project (yarn or bun dev)

**Comment by marco-souza** [comment]
> Just made me want to use it everywhere

@vzsoares - It is safe as soon as we don't share the password with anyone haha - for small projects it is safe enough
