### ISSUE TITLE
[ref] migrate Theme Switcher to TailwindCSS

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#184]
# Description

This task aims to replace the current theme switcher with a new one made for Tailwind

We need to:
- [ ] understand how tailwind dark mode works
- [ ] plan how we'll implement that in tailwind
- [ ] refactoring all places where we use `useColorModeValue`
  - [ ] replace and remove the hook

## Definition of done

- no dark mode dependency on chakra
- no `useColorModeValue`

## Useful Links
- https://dev.to/danhawkins/a-simple-theme-switcher-in-react-for-tailwind-css-1349
- https://tailwindcss.com/docs/dark-mode

**Comment by Joel-leal** [comment]
Let's go?

**Comment by marco-souza** [comment]
Let's go!
