### ISSUE TITLE
Adicionar dados da comunidade

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#44]
Adidionar uma sessão para compartilhar dados sobre a comundiade.

- bolsas pagas
- mentorandos contratados
- membros ativos

**Comment by vzsoares** [comment]
acho que talvez uma pagina /achievements contendo uma timeline sobre as contrataçoes e salientar o uso da bolsa se teve. e membros ativos ja tem a /team

**Comment by marco-souza** [comment]
closing in favor of #58
