### ISSUE TITLE
Refactor LinksTrasalated

### ISSUE THREAD

**Issue by Filipe-barbosa** [podcodar/webapp#51]
- fix typo name
- body is empty
- move the title to its body

**Comment by marco-souza** [comment]
Acho que o typo já está resolvido, temos que ver os outros problemas

**Comment by vzsoares** [comment]
nao entendi direito esse issue

**Comment by marco-souza** [comment]
Acho que ela nao da no backlog. Estamos trabalhandoa penas nas que estao para serem feitas

**Comment by marco-souza** [comment]
https://github.com/orgs/podcodar/projects/4
