### ISSUE TITLE
criar sessão de testemunhos

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#58]
- bolsas pagas
- mentorandos contratados
- testemunhos

**Comment by fmagesty** [comment]
galera, tem algum modelo de design especifico ou alguma ideia (um norte, sei la) pra essa task? to a mt tempo sem vir no projeto entao nao sei se to olhando no lugar certo. se alguem souber

vlw

**Comment by marco-souza** [comment]
Pior que nao viu, essa tarefa ainda tem que ser definida. Se quiser pesquisar algum model e sugerir algo, tamo aceitando

**Comment by vzsoares** [comment]
creio q da pra somar com a issue #44

**Comment by vzsoares** [comment]
tenho uma sugestao para esse issue : 
- criar uma pagina /achievements 
- nessa , criar um layout similar a midias sociais ( cards ) contendo as informaçoes desejadas

so que fiquei com uma duvida de como fazer o armazenamento e alimentaçao de dados para a pagina.
 vi e acho q os dados estao no firebase mas nao sei como explorar o projeto no firebase

**Comment by vzsoares** [comment]
exemplo bem chulo

![image](https://user-images.githubusercontent.com/86134825/168931364-f04b9f45-7d34-43e0-8fba-1e14837c69ba.png)

**Comment by marco-souza** [comment]
Boa! Eu acho que rola da gente tentar pegar algum template de chakra que tiver legalzinho e adaptar. 
Pra evita da gente gastar muito tempo com UI no momento.

Essa sessão ficaria legal na home page por hora

**Comment by marco-souza** [comment]
Quebrei essa tarefa em algumas outra na board. Acho que podemos fechar isso e seguir com a feature
