### ISSUE TITLE
Contextualização sobre React

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#62]
# Description

Com time de desenvolvimento do webapp da PodCodar, precisamos passar por alguns conceitos básicos das ferramentas que usamos. 

O objetivo dessa tarefa é fazer uma **apresentação para contextualizar** os membros do time sobre **React**.

## Critérios de Aceite

Preparar e apresentar os seguintes tópicos
- DOM e o Virtual DOM
- JSX
- props
- states

## Sub-tasks

- [ ] Preparar apresentação **no notion** (temos uma sessão de react na [eng wiki][1])
- [x] Apresentar para o time (se lembre de **gravar a apresentação**) 

[1]: https://www.notion.so/podcodar/Engineering-Wiki-597eb2a7a0534547b1e0f9a2e48d22d2

**Comment by Filipe-barbosa** [comment]
Não rolou  de gravar mas  a para a proxima apresentação isso será desenvolvivdo

**Comment by marco-souza** [comment]
Vamos criar uma tarefa na proxima sprint para documentar melhor o material de React
